version: 2

sources:
  - name: shelter_data
    database: 
    schema: shelter_data

    tables:
      - name: shelter_data_export
        description: Data sourced from shelters
      - name: zipcode_data
        description: Data pulled from USPS https://www.unitedstateszipcodes.org/zip-code-database/
      - name: shelter_photos
        description: Incrementally loaded photo url table
        columns:
          - name: photo_id
            tests:
              - unique
              - not_null
